# Generated by Django 3.2.9 on 2022-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Название')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('description', models.TextField(default='Описание отсутствует', null=True, verbose_name='Описание')),
                ('duration', models.IntegerField(default=0, max_length=15, verbose_name='Длительность')),
                ('url', models.CharField(max_length=10, unique=True, verbose_name='Ссылка на просмотр')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('views', models.IntegerField(blank=True, default=0, max_length=15, verbose_name='Количество просмотров')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступность')),
                ('video', models.FileField(upload_to='video/')),
                ('screensaver', models.FileField(upload_to='screensavers/')),
            ],
        ),
    ]
