# Generated by Django 3.2.9 on 2022-05-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='views',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='screensaver',
            field=models.FileField(upload_to='screensavers/', verbose_name='Заставка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(upload_to='video/', verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('view_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('record', models.FileField(upload_to='records/', verbose_name='Запись')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.advertisement')),
            ],
        ),
    ]
