# Generated by Django 3.2.9 on 2022-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20220514_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Пользователь'),
        ),
    ]
