# Generated by Django 3.2.9 on 2022-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_advertisement_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='brand',
            field=models.CharField(max_length=20, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='screensaver',
            field=models.FileField(max_length=255, upload_to='screensavers/', verbose_name='Заставка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(max_length=255, upload_to='video/', verbose_name='Видео'),
        ),
    ]
