# Generated by Django 3.2.9 on 2022-05-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20220518_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Пользователь'),
        ),
    ]
