# Generated by Django 3.2.9 on 2022-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_analyzed',
            field=models.BooleanField(default=False, verbose_name='Проанализирована'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность'),
        ),
    ]
